.TH PUPPET-LINT "1" "September 2011" "puppet-lint 0.1.4" "User Commands"
.SH NAME
puppet-lint \- check puppet manifests for style guide conformity
.SH DESCRIPTION
Puppet\-lint
.SS "Basic Command Line Usage:"
.IP
puppet\-lint [OPTIONS] [PATH]
.TP
PATH
The path to the Puppet manifest.
.SH OPTIONS
.TP
\fB\-\-version\fR
Display current version.
